### ISSUE TITLE
OOM Error on Windows 11 24GB GPU (RTX 3090) with sample_gpu_poor.py Despite Following Low VRAM Guidelines

### ISSUE THREAD

**Issue by Vibecoder9000** [Tencent/HunyuanCustom#8]
**System Information:**
*   **OS:** Windows 11 (Version 10.0.22631.5262)
*   **GPU:** NVIDIA RTX 3090 (24GB VRAM)
*   **CUDA Version (from NVIDIA Driver):** 12.9.40
*   **CUDA Toolkit Version:** 12.8
*   **Python Version:** 3.10.9 (via Conda)
*   **PyTorch Version:** 2.7.0+cu126 (installed via pip from PyTorch index)
*   **`diffusers` Version:** 0.33.0 (installed as per GitHub Issue #6 recommendation for HunyuanCustom)
*   **`transformers` Version:** 4.41.2 (installed as per GitHub Issue #6 recommendation for HunyuanCustom)
*   **`opencv-python` Version:** 4.11.0.86 (reinstalled to be compatible with NumPy 2.x)
*   **`numpy` Version:** 2.2.5

**Problem Description:**
I am consistently encountering CUDA Out of Memory (OOM) errors when trying to run `hymm_sp/sample_gpu_poor.py` on my Windows 11 system with an RTX 3090 (24GB VRAM). This occurs even when attempting to use settings that align with the documentation's claim that a "minimum GPU memory required is 24GB for 720px1280px129f but very slow."

The OOM error consistently occurs during the initial model loading phase, specifically when `pipeline.to(device)` is called within `hymm_sp/diffusion/__init__.py` (this call is part of the model setup triggered by `HunyuanVideoSampler.from_pretrained` and `load_diffusion_pipeline`), even when `pipeline.enable_model_cpu_offload(gpu_id=0)` should be active due to the `--cpu-offload` flag.

**Error Signature (when using FP8 checkpoint, e.g., `..._fp8.pt` and `--use-fp8`):**
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 46.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 23.13 GiB is allocated by PyTorch, and 122.53 MiB is reserved by PyTorch but unallocated.
```
This exact error signature appears regardless of `--sample-n-frames` (tried 129, 32, 9, 1) or `--video-size` (tried 720x1280, 512x896, 360x640, 128x224) when using the FP8 checkpoint.

**Error Signature (when using FP32 checkpoint, e.g., `...states.pt`, no `--use-fp8`, at 720p):**
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 23.07 GiB is allocated by PyTorch, and 82.39 MiB is reserved by PyTorch but unallocated.
```

**Steps Taken & Observations:**
1.  Cloned the repository.
2.  Created a Conda environment with Python 3.10.9.
3.  Installed PyTorch 2.7.0+cu126.
4.  Installed dependencies (initially from `requirements.txt`, then updated specific libraries).
5.  Successfully compiled and installed `flash-attention v2.6.3`.
6.  Downloaded all pretrained models and placed them in `./models` correctly.
7.  Updated `diffusers` to `0.33.0` and `transformers` to `4.41.2` as specifically recommended in GitHub Issue #6 for HunyuanCustom by a project collaborator.
8.  Ensured `opencv-python` is compatible with `numpy 2.2.5` (current version `opencv-python-4.11.0.86`).
9.  Set environment variables: `CPU_OFFLOAD=1`, `PYTHONPATH`, `MODEL_BASE`.
10. Consistently used the `--cpu-offload` flag with `sample_gpu_poor.py`.
11. Tried various combinations of `--video-size`, `--sample-n-frames`, using the FP8 checkpoint (`--use-fp8`), and the full precision checkpoint.
12. Tested the command derived from `run_gradio.sh` (which calls `sample_gpu_poor.py` with 720p, 129 frames, FP8, and `--use-deepcache 1`).
13. The PyTorch warning `UserWarning: expandable_segments not supported on this platform` is always present during execution.
14. A diagnostic test forcing both text encoders to `clipL` (`--text-encoder clipL --text-encoder-2 clipL`) *did allow the model to load without OOM*, but then failed later with `ValueError: Unsupported data type: image`. This strongly suggests the Llava-Llama-3-8B model's VRAM footprint during initial loading is the primary component exceeding available VRAM.

**Hypothesis:**
The combined VRAM requirement of the auxiliary models (primarily Llava-Llama-3-8B, VAE, CLIP-L) during the `pipeline.to(device)` or `enable_model_cpu_offload` setup phase exceeds the available ~23.5GB VRAM on my Windows 11 system. The offloading mechanisms, while active as per logs (`vae: cpu_offload=1`, `text_encoder: cpu_offload=1`, `models: cpu_offload=1`), may not be sufficiently reducing the VRAM footprint of these *auxiliary models* during this critical initial setup on a Windows 11 environment, unlike on Linux where user `@colorAi` (Issue #6) reported eventual success (though very slow) on a 24GB card after the same library updates. The unavailability of the `expandable_segments` CUDA allocator feature on Windows (as warned by PyTorch) might also be a contributing factor if it's crucial for fitting into 24GB on Linux.

**Request:**
Could the development team please provide:
1.  Confirmation if the "minimum 24GB for 720p" specification was validated on Linux or Windows?
2.  The exact PyTorch version, system-wide CUDA Toolkit version (if any), NVIDIA driver version, and full list of critical library versions (e.g., from `pip freeze` of the working environment) used for the 24GB minimum validation?
3.  Any specific environment variables (beyond `CPU_OFFLOAD=1`), launch configurations, or known OS-specific considerations required to achieve this on a 24GB GPU, particularly if there are differences for Windows users?
4.  Insight into whether the `expandable_segments` CUDA allocator feature is critical for the 24GB claim and if its absence on some Windows PyTorch builds could explain this discrepancy.

Thank you for your time and this promising project.

**Comment by AndrewBeniston** [comment]
Hey there, would mind giving insight as to how you are trying to run it up on windows - as I know the .sh files are running up the .py files but I am struggling to get anything going on Windows

**Comment by zhouzhengguang** [comment]
@Vibecoder9000

**Comment by zhouzhengguang** [comment]
Hi, @Vibecoder9000 Thank you for your interest. Here, we made a mistake, `pipeline.to(device)` should be skipped, I hope you can try again.
We have fixed this bug here
```
https://github.com/Tencent/HunyuanCustom/blob/main/hymm_sp/diffusion/__init__.py#L24
```

**Comment by Cazforshort** [comment]
Mine just says killed for the same rig:

> export MODEL_BASE="./models"
export CPU_OFFLOAD=1
export PYTHONPATH=./
python hymm_sp/sample_gpu_poor.py \
    --input './assets/images/seg_woman_01.png' \
    --pos-prompt "Realistic, High-quality. A woman is drinking coffee at a café." \
    --neg-prompt "Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion, blurring, text, subtitles, static, picture, black border." \
    --ckpt ${MODEL_BASE}"/hunyuancustom_720P/mp_rank_00_model_states_fp8.pt" \
    --video-size 720 1280 \
    --seed 1024 \
    --sample-n-frames 129 \
    --infer-steps 30 \
    --flow-shift-eval-video 13.0 \
    --save-path './results/cpu_720p' \
    --use-fp8 \
    --cpu-offload 
TrtRunner or EngineFromBytes is not available, you can not use trt engine
vae: cpu_offload=1, DISABLE_SP=0
text_encoder: cpu_offload=1
models: cpu_offload=1, DISABLE_SP=0
2025-05-15 19:59:22.876 | INFO     | hymm_sp.inference:from_pretrained:59 - Got text-to-video model root path: ./models/hunyuancustom_720P/mp_rank_00_model_states_fp8.pt
2025-05-15 19:59:22.876 | INFO     | hymm_sp.inference:from_pretrained:67 - Building model...
========================= build model =========================
Killed

**Comment by zhouzhengguang** [comment]
> > 2025-05-15 19:59:22.876 | INFO     | hymm_sp.inference:from_pretrained:59 - Got text-to-video model root path: ./models/hunyuancustom_720P/mp_rank_00_model_states_fp8.pt
> > 2025-05-15 19:59:22.876 | INFO     | hymm_sp.inference:from_pretrained:67 - Building model...
> > ========================= build model =========================
> > Killed

There may still be insufficient gpu memory. Please confirm that you are using the latest code and skip `pipeline.to(device)` in `HunyuanCustom/blob/main/hymm_sp/diffusion/__init__.py#L24`.
